name: Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@semihorhanbio"

      - name: Change to package directory
        run: cd shared # Replace with your actual folder name

      - run: npm install
        working-directory: ./shared

      - run: npm run build
        working-directory: ./shared

      - name: Create .npmrc file
        run: |
          echo @semihorhanbio:https://npm.pkg.github.com/ > build/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> build/.npmrc
        working-directory: ./shared

      - name: Fix package.json
        run: npm pkg fix
        working-directory: ./shared

      - run: npm publish
        working-directory: ./shared/build
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
